### ISSUE TITLE
Add OM-Cookie-Manager Cookie in Cookie Option List

### ISSUE THREAD

**Issue by webcande** [Xippo/OM-Cookie-Manager#5]
Hi, thanks for your extension!

In the FE options the visitor can see all the cookies delivered by the website. But what about the OM-Cookie-Manager Cookie itself? It will not get listed although it will be fired. 

I may could add it to the Cookie records in the backend options without entering html but I wonder if you think it is not needed to list it?

Kind regards

**Comment by Xippo** [comment]
Hi Webcande,
thx for your question. For my interpretation of the GDPR, you should list the cookie and explain what his purpose is. But i think as well, that the omcookiemanager cookie is part of the essential regulation(so no active consent is nedded), because is needed to log the consent of users and regulate what kind of js is loaded for the user, so it is essential for the website as well. But im not a data protection officer or a lawyer ;).

As you pointed out, the extension user can easily setup the cookie without html, so it will be listed for the website user inside the info table. You suggest a different approach? Maybe I can add some text to the readme. In the docs on my page I mention the use of a own cookie, but also there i can give this point a bit more depth. Something like automatic listing, im not a fan of. In this case we will need a general description in many languages, not everyone will list this cookie, so we need settings etc etc.

**Comment by webcande** [comment]
Hi Xippo,
thanks for your brief description. As I understand the topic, the listing shall list **all** cookies, which are set, even if they are essential. But I may be wrong. 
I will add "your" cookie to my list without html and that will help me, as far if the extension is not complaining about not given html entry. Will try next time. When there is an issue, then I will report here again.
Bye
